/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module multiplier16_34 (
    input [15:0] x,
    input [15:0] y,
    input [5:0] alufn,
    output reg [15:0] s,
    output reg error
  );
  
  
  
  reg [15:0] result;
  
  always @* begin
    error = 1'h0;
    
    case (alufn[0+1-:2])
      2'h0: begin
        result = x * y;
        s = result;
      end
      default: begin
        s = 16'h0000;
      end
    endcase
  end
endmodule
