/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter16_31 (
    input [15:0] x,
    input [15:0] y,
    input [5:0] alufn,
    output reg [15:0] result
  );
  
  
  
  always @* begin
    
    case (alufn[2+1-:2])
      2'h0: begin
        
        case (alufn[0+1-:2])
          2'h0: begin
            result = x << y[0+3-:4];
          end
          2'h1: begin
            result = x >> y[0+3-:4];
          end
          2'h3: begin
            result = $signed(x) >>> y[0+3-:4];
          end
          default: begin
            result = 16'h0000;
          end
        endcase
      end
    endcase
  end
endmodule
